language: php
dist: bionic

services:
  - xvfb

cache:
  directories:
    - $HOME/.composer/cache
    - jar

php:
  - 7.2
  - 7.3

env:
  global:
    - DISPLAY=:99.0
    - SELENIUM_MAJOR_VERSION="3.141"
    - SELENIUM_MINOR_VERSION="59"
    - GECKODRIVER_VERSION="v0.26.0"
    - WEBDRIVER=selenium
  jobs:
    - BROWSER_NAME=chrome CHROMEDRIVER=0
    - BROWSER_NAME=firefox GECKODRIVER=0
    - BROWSER_NAME=chrome CHROMEDRIVER=1
    #- BROWSER_NAME=firefox GECKODRIVER=1

jobs:
  fast_finish: true

install:
  - travis_retry composer install --no-interaction --prefer-dist
  - mkdir -p ./logs
  - |
    if [ "$BROWSER_NAME" = "chrome" ]
    then
      mkdir chromedriver
      CHROME_VERSION=`google-chrome-stable --version | awk '{print $NF}' | sed 's/\.[0-9]*$//'`
      echo "Chrome version is $CHROME_VERSION"
      CHROMEDRIVER_VERSION=`curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION`
      echo "chromedriver version is $CHROMEDRIVER_VERSION"
      wget -q -t 3 https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
      unzip chromedriver_linux64 -d chromedriver
      export CHROMEDRIVER_PATH=$PWD/chromedriver/chromedriver
    fi
  - |
    if [ "$BROWSER_NAME" = "firefox" ]
    then
    mkdir geckodriver
      wget -q -t 3 https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
      tar xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz -C geckodriver
      export PATH="$PATH:`pwd`/geckodriver"
    fi
  - |
    if [ "$WEBDRIVER" = "selenium" ] && [ ! -f jar/selenium-server-standalone.jar ]
    then
      mkdir -p jar
      wget -q -t 3 -O jar/selenium-server-standalone.jar https://selenium-release.storage.googleapis.com/$SELENIUM_MAJOR_VERSION/selenium-server-standalone-$SELENIUM_MAJOR_VERSION.$SELENIUM_MINOR_VERSION.jar
    fi

before_script:
  - |
    if [ "$GECKODRIVER" = "1" ]
    then
      geckodriver/geckodriver &> ./logs/geckodriver.log &

    elif [ "$CHROMEDRIVER" = "1" ]
    then
      $CHROMEDRIVER_PATH --port=4444 --url-base=/wd/hub &> ./logs/chromedriver.log &

    elif [ "$WEBDRIVER" = "selenium" ]
    then
      java -Dwebdriver.chrome.driver="$PWD/chromedriver/chromedriver" -Dwebdriver.gecko.driver="$PWD/geckodriver/geckodriver" -jar jar/selenium-server-standalone.jar -log ./logs/selenium.log &
    fi
  - vendor/bin/mink-test-server > ./logs/php-server.log 2>&1 &
  - sleep 5

script: ./vendor/bin/phpunit --testdox

after_script:
  - if [ -f ./logs/selenium.log ]; then cat ./logs/selenium.log; fi
  - if [ -f ./logs/php-server.log ]; then cat ./logs/php-server.log; fi

after_failure:
  - if [ -f ./logs/selenium.log ]; then cat ./logs/selenium.log; fi
  - if [ -f ./logs/php-server.log ]; then cat ./logs/php-server.log; fi
